[project]
name = "mobile"
version = "0.0.1"
description = "Mobile"
authors = [
  { name = "Quantbit", email = "pradip.jadhav@erpdata.in" }
]
requires-python = ">=3.10"
dependencies = []

[tool.frappe]
app_name = "mobile"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"